name: 'my_dbt_project'
version: '1.0.0'
config-version: 2
profile: 'snowflake_profile'
model-paths: ['models']
target-path: 'target'
clean-targets: ['target','dbt_packages']
models:
  my_dbt_project:
    staging:
      +materialized: view
    marts:
      +materialized: table
